### ISSUE TITLE
Seems to create never ending writes to manifest_tmp.json

### ISSUE THREAD

**Issue by ntoff** [fredemmott/StreamDeck-MicMute#5]
With this plugin installed, streamdeck.exe seems to constantly write to manifest_tmp.json, presumably setting and re-setting the muted state over and over again.

![image](https://user-images.githubusercontent.com/9030085/53156349-f20caa80-360a-11e9-9e51-2903acb68669.png)

Upon uninstalling this particular plugin, the never ending writes cease. I also tested with only this plugin installed and the same behaviour occurred.

Windows 10 pro 
SD software 4.0.2.9798
Mic Mute version 1.1

**Comment by fredemmott** [comment]
@Timac is it expected that doing no-op SetState calls spam the disk a bunch?

**Comment by fredemmott** [comment]
and, what exactly do you mean by 'constantly'? the plugin only wakes up 4 times a second

**Comment by Timac** [comment]
> @Timac is it expected that doing no-op SetState calls spam the disk a bunch?

Calling SetState with the current state will indeed save the profile to disk. While this could be optimized, this should only cause one write to disk and not multiple writes.

**Comment by fredemmott** [comment]
Thanks - I found a callback API, so 2.0 will address this by not polling.
